[tool.poetry]
name = "arr"
version = "0.1.0"
description = ""
authors = ["Iago Corrêa"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numba = "^0.59.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
